### ISSUE TITLE
Same-origin local websocket request blocked

### ISSUE THREAD

**Issue by thomazz-nl** [bromite/bromite#1327]
### Bromite version

Version: `92.0.4515.134`
Arch: `arm64`
Android version: `11`
Device model: `KB2003` (OnePlus 8T)

### Flags

These are the flags changed under `chrome://flags`:
None. There are no blue-highlighted flags indicating activated flags.

### Is this bug about the SystemWebView?
No. While this issue is present on SystemWebView too, this bugreport is based on regular Bromite.

### Is the bug reproducible with latest version?
Yes, 92.0.4515.134 is the most recent version at the time of writing.

### Can the bug be reproduced with corresponding Chromium version?
No, in Chromium this issue does not occur.

### Is this bug happening in an incognito tab?
No, in a regular tab. It will also happen in an incognito tab.

### Allow ads for the site; is the bug caused by the adblocker?
No, the bug still occurs when allowing ads.

### Is the bug a crash?
No.

### Describe the bug
A website hosted on the local area network, visited by it's domain name (resolving to a local ip-address), that tries to open a WebSocket connection from the browser to it's origin (so same-origin AND local request) is denied by Bromite. This is likely to be caused by the introduction of the [Block private networks scanning (gateway attacks) patch](https://github.com/bromite/bromite/issues/590). Also described in [#1320](https://github.com/bromite/bromite/issues/1320)

### Steps to reproduce the bug
Requirements:
- Valid certificate+key for a domain name.
- Docker (with Docker Compose)

Steps:

1. Create a test directory on a Docker host in your local network.
2. Place your certificate files in the directory (if they're not named fullchain.pem and privkey.pem, adjust accordingly).
3. Create a file in the directory named docker-compose.yaml, add the following content to the file and save it:
```yaml
---
version: "3.8"
services:
    hass:
        container_name: hass
        environment:
            PGID: 0    # Change if running as root is not desired. The GID should correspond with the owning group of the certificate files.
            PUID: 0    # Change if running as root is not desired. The UID should correspond with the owning user of the certificate files.
            TZ: Europe/Amsterdam
        image: linuxserver/homeassistant:version-2021.7.4
        ports:
            - "8123:8123"
        secrets:
            - fullchain.pem
            - privkey.pem
#        volumes:
#            - ./volumes/config:/config:rw
secrets:
    fullchain.pem:
        file: ./fullchain.pem
    privkey.pem:
        file: ./privkey.pem
...
```

4. Open a terminal and navigate to the created directory. Execute the following commands:
```shell
docker-compose up -d hass
sleep 30
docker exec hass ash -c "printf 'http:\n    ssl_certificate: /run/secrets/fullchain.pem\n    ssl_key: /run/secrets/privkey.pem' >> /config/configuration.yaml"
docker-compose restart hass
```
5. Make sure the service is accessible on ```https://docker-host-ip:8123/``` (a certificate warning can be expected, that's ok at this point).
6. Allow the Bromite client to resolve the domain name corresponding to your certificate to the local IP of the Docker host. This can be done in multiple ways, starting with the easiest:
    - Making changes to the hosts file on the device ([Android](https://www.google.com/search?q=how+to+edit+hosts+file+on+android))
    - Pi-Hole - using the local DNS settings.
    - Running a local DNS server and adding the appropriate domain records.
7. Visit ```https://[yourdomainname]:8123/``` on Chromium or another working browser.
8. Fill the registration form (test/test/test/test) and hit "create account". Finish the onboarding process (click next, next finish) until a login screen is presented.
9. Start Bromite, attach a debugger, visit ```https://[yourdomainname]:8123/``` and attempt to login by entering test/test.

Resulting error:
```Exception "Uncaught (in promise) DOMException: Failed to construct 'WebSocket': Access to this address is not allowed."```
on calling ```const d = new WebSocket(r);``` where r is ```wss://[yourdomainname]:8123/api/websocket``` and window.location.origin is ```https://[yourdomainname]:8123```.

### Expected behavior
I expected websites served from a host on the local network to be allowed to create websockets when requestor_space is equal to target_space.
Example: visiting ```https://home.mydomain.tld``` (on 192.168.1.100) would be allowed to have traffic to ```wss://home.mydomain.tld/api/websocket```
